### ISSUE TITLE
Long commands in CLI return a (wrong) error

### ISSUE THREAD

**Issue by feyrian** [Tau-Coin/taucoin#11]
Using taucoin-cli if a command takes more than 15 minutes to respond, (typically the generatetoaddress command with a high number of blocks) it returns this error:
`error: couldn't connect to server`
**But** taucoind is still running and the command still runs too.

**Comment by Morpheusai** [comment]
It's fine, the taucoin-cli communicates with taucoind process in a  time-limited connection. The taucoin-cli's  command is sended to taucoind process, and will keep connection for a while, if there is no reply, the connection will be  disconnected and return the error: couldn't connect to server.

**Comment by feyrian** [comment]
Is there a way to at least change the return message, to be more specific, like 
`warning: connection lost to server, but the command is still running`
Something like that ?
