### ISSUE TITLE
Cant connect to network, cant get blocks, source unavilable

### ISSUE THREAD

**Issue by Td10tsk** [Tau-Coin/taucoin#14]
ERROR: AcceptBlockHeader: Consensus: ContextualBlockHeader ... bad-basetargetbits, incorrect proof of tx (code 16)
ERROR: invalid header received
BAN TRESHOLD EXCEEDED

Can anyone help me, i just build wallet in 16.04, it starts but cant sync!

**Comment by cuitaixiang** [comment]
Your wallet cannot accept the block header,because its basetarget is incorrect! Could you give me more information?Are you using the latest code and how do you run the taucoin core?

**Comment by Td10tsk** [comment]
> 
> 
> Your wallet cannot accept the block header,because its basetarget is incorrect! Could you give me more information?Are you using the latest code and how do you run the taucoin core?

1) I using latest code, compiled yesterday from :
`git clone https://github.com/Tau-Coin/taucoin.git`

2) Run taucoin core by taucoin-qt executable file (end even try console version - taucoind, result the same)

**Comment by Td10tsk** [comment]
2018-09-28 11:07:01 receive version message: /Satoshi:0.13.0/: version 70014, blocks=28190, us=(there_was_my_ip):56195, peer=1
2018-09-28 11:07:06 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 4fc99db04003b4d0a2c31c45d8f54fd65426f570fd4d172b5bdd3b6969bbe322, bad-basetargetbits, incorrect proof of tx (code 16)
2018-09-28 11:07:06 Misbehaving: (node_ip_was_there):8686 (0 -> 50)
2018-09-28 11:07:06 ERROR: invalid header received
2018-09-28 11:07:06 ProcessMessages(headers, 518739 bytes) FAILED peer=1

**Comment by cuitaixiang** [comment]
> 2018-09-28 11:07:01 receive version message: /Satoshi:0.13.0/: version 70014, blocks=28190, us=(there_was_my_ip):56195, peer=1
> 2018-09-28 11:07:06 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 4fc99db04003b4d0a2c31c45d8f54fd65426f570fd4d172b5bdd3b6969bbe322, bad-basetargetbits, incorrect proof of tx (code 16)
> 2018-09-28 11:07:06 Misbehaving: (node_ip_was_there):8686 (0 -> 50)
> 2018-09-28 11:07:06 ERROR: invalid header received
> 2018-09-28 11:07:06 ProcessMessages(headers, 518739 bytes) FAILED peer=1

Could you show me your current block height?

**Comment by Td10tsk** [comment]
> Could you show me your current block height? You can get your block number in taucoin-qt:Help->Debug window->information.

block number: 0
last block time: friday june 15 12:55:54 2018

**Comment by cuitaixiang** [comment]
I think there are some problems in your data directory.I suggest you remove it by "rm -rf .taucoin" in you home directory .Then, you can run taucoin core again.

**Comment by cuitaixiang** [comment]
> > Could you show me your current block height? You can get your block number in taucoin-qt:Help->Debug window->information.
> 
> block number: 0
> last block time: friday june 15 12:55:54 2018

I think there are some problems in your data directory.I suggest you remove it by "rm -rf .taucoin" in you home directory .Then, you can run taucoin core again.

**Comment by Td10tsk** [comment]
> I think there are some problems in your data directory.I suggest you remove it by "rm -rf .taucoin" in you home directory .Then, you can run taucoin core again.
I make fresh installation (compile from source), and change dir/ remove dir doesnt help. Still wrong behaviour.

**Comment by cuitaixiang** [comment]
> > I think there are some problems in your data directory.I suggest you remove it by "rm -rf .taucoin" in you home directory .Then, you can run taucoin core again.
> > I make fresh installation (compile from source), and change dir/ remove dir doesnt help. Still wrong behaviour.

It really puzzles me. I have tried many times, and everything is OK. Would you send me your log file? You can run the taucoin core like "./taucoind -debug=1", then send "debug.log" which is in .taucoin directory to my email: cuitaixiang@aliyun.com. Thanks.
