### ISSUE TITLE
tau con 10$

### ISSUE THREAD

**Issue by Catalizer123** [Tau-Coin/taucoin#16]

**Comment by rupmedia24** [comment]
Good

**Comment by feyrian** [comment]
@Catalizer123 @rupmedia24 Guys this is not the place. Here is for code issues, technical matters about the taucoin wallet. Please don't spam here.
@qingxueyunfeng would you close/delete this "issue", thks

**Comment by anai212** [comment]
you mean ?

**Comment by IIIYMBETPA** [comment]
Yes--Отправлено из мобильной Яндекс.Почты12.10.2018, 06:49, "anai212" <notifications@github.com>:you mean ?

**Comment by anai212** [comment]
GOOD

**Comment by IIIYMBETPA** [comment]
yes12.10.2018, 07:49, "anai212" <notifications@github.com>:you mean ?

**Comment by Bintorojaya** [comment]
Good projeck

**Comment by IIIYMBETPA** [comment]
good project https://altexch.io/?ref=230531 10$ for registration12.10.2018, 07:24, "Nurmanto" <notifications@github.com>:Good

**Comment by IIIYMBETPA** [comment]
good project https://altexch.io/?ref=230531 100 token for registration12.10.2018, 07:24, "Nurmanto" <notifications@github.com>:Good

**Comment by pucuk11** [comment]
good

**Comment by IIIYMBETPA** [comment]
Thanks )Good project http://altexch.io/?ref=230531 10$ sign ap--Отправлено из мобильной Яндекс.Почты14.10.2018, 05:02, "pucuk11" <notifications@github.com>:good

**Comment by gorzansaeid** [comment]
good💕

**Comment by Morpheusai** [comment]
Thank you.Here is just for code issues, technical matters
