### ISSUE TITLE
Address not allowed to forge

### ISSUE THREAD

**Issue by Td10tsk** [Tau-Coin/taucoin#18]
I use command generate to address, but it throw me this error. How can i start be mining leader?

**Comment by Syakieb** [comment]
0xDF4c6cA14cDDFBe9812dfDb8e7e85A61Af01a129

**Comment by Td10tsk** [comment]
sendtoaddress <adr> "0" will produce error: "invalid amount"

**Comment by cuitaixiang** [comment]
> sendtoaddress "0" will produce error: "invalid amount"
If you want to be a miner, you can send a signal transaction(zero value transaction) to your own address. And signal transaction only can be sent by qt wallet so far.

**Comment by feyrian** [comment]
@Td10tsk this is a code issue tracker, not a helpdesk channel. Go to Taucoin Discord to get help.
Thanks to close this issue.
