### ISSUE TITLE
command "generate 1" return emty json

### ISSUE THREAD

**Issue by Td10tsk** [Tau-Coin/taucoin#19]
generate 1
[
]

**Comment by cuitaixiang** [comment]
Please use the generatetoaddress command to specify the address for mining, and that address needs to be a miner first.

**Comment by feyrian** [comment]
@Td10tsk  this is a code issue tracker, not a helpdesk channel. Go to Taucoin Discord to get help.
Thanks to close this issue.

**Comment by Bintorojaya** [comment]
Good projeck https://www.taucoin.io/account/login?referralURL=80452f122c2de0d803d4365bd67b7e3e197649b8382d86d7f0a49733214e3397

**Comment by IIIYMBETPA** [comment]
tanks .good procekt https://altexch.io/?ref=230531 10$ for registration13.10.2018, 17:49, "Bintorojaya" <notifications@github.com>:Good projeck https://www.taucoin.io/account/login?referralURL=80452f122c2de0d803d4365bd67b7e3e197649b8382d86d7f0a49733214e3397
