### ISSUE TITLE
Come and Join 

### ISSUE THREAD

**Issue by Kris2310** [Tau-Coin/taucoin#22]
https://www.taucoin.io/account/login?referralURL=a6c234885e6315689bd546d26c91f96e889a7b924a92bd26371b5657602b4325

**Comment by IIIYMBETPA** [comment]
Tanks)!Good project http://altexch.io/?ref=230531 10$ sign ap--Отправлено из мобильной Яндекс.Почты14.10.2018, 04:27, "Kris2310" <notifications@github.com>:https://www.taucoin.io/account/login?referralURL=a6c234885e6315689bd546d26c91f96e889a7b924a92bd26371b5657602b4325
