### ISSUE TITLE
go go go taucoin $0.1

### ISSUE THREAD

**Issue by antopunya** [Tau-Coin/taucoin#24]
i hope taucoin next price $0.1/tau...go go taucoin

**Comment by Td10tsk** [comment]
where tau coin exchange?

**Comment by IIIYMBETPA** [comment]
Tanks)))FREE 100 token http://altexch.io?ref=230531 for sign up14.10.2018, 18:16, "Td10tsk" <notifications@github.com>:where tau coin exchange?

**Comment by mK7768** [comment]
Im nice by TAU    TAU    TAU   

YOHHOOOOOOO

**Comment by mK7768** [comment]
Im nice by TAU    TAU    TAU   

YOHHOOOOOOO

**Comment by mK7768** [comment]
Im nice by TAU    TAU    TAU   

YOHHOOOOOOO

**Comment by mK7768** [comment]
Im nice by TAU    TAU    TAU   

YOHHOOOOOOO

**Comment by mK7768** [comment]
Im nice by TAU    TAU    TAU   

YOHHOOOOOOO

**Comment by IIIYMBETPA** [comment]
Thanks )))FREE  100 token http://altexch.io?ref=23053117.10.2018, 23:30, "mK7768" <notifications@github.com>:Im nice by TAU    TAU    TAU
YOHHOOOOOOO
