### ISSUE TITLE
God projects #taucoin

### ISSUE THREAD

**Issue by relic93** [Tau-Coin/taucoin#25]
https://www.taucoin.io/account/login?referralURL=11806051800ab92c9f6ff9d1e5b051fee07b924dcf7af63dfe18503fe3866c51

**Comment by IIIYMBETPA** [comment]
tanhks)))FREE 100 coin http://altexch.io?ref=230531 for sign up14.10.2018, 20:29, "relic93" <notifications@github.com>:https://www.taucoin.io/account/login?referralURL=11806051800ab92c9f6ff9d1e5b051fee07b924dcf7af63dfe18503fe3866c51
