### ISSUE TITLE
tau tau go go

### ISSUE THREAD

**Issue by kais0106** [Tau-Coin/taucoin#27]
Please copy and use following link to refer TAU and accumulate your rewards. 
Please write anything nice about TAU, or just write: 
"Please check-out TAU coin, a novel proof of transaction consensus based crypto currency !"

https://www.taucoin.io/account/login?referralURL=4943c6decb3b2e92f167fb8de63e93a3d21a00b5f8c43500cbb2c614f727749f

**Comment by kais0106** [comment]
go go go
1,$ tau tau 😊

**Comment by klix72** [comment]
About the wallet where we échange about the rates?
What is this story about some investment b4 to withdraw?

**Comment by IIIYMBETPA** [comment]
Thanks )))FREE 100 token http://altexch.io?ref=23053117.10.2018, 17:37, "klix72" <notifications@github.com>:About the wallet where we échange about the rates?
What is this story about some investment b4 to withdraw?

**Comment by IIIYMBETPA** [comment]
Thanks )))FREE 100 token http://altexch.io?ref=23053117.10.2018, 04:07, "kais0106" <notifications@github.com>:go go go
1,$ tau tau <g-emoji class="g-emoji" alias="blush" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f60a.png">😊

**Comment by Morpheusai** [comment]
Thank you.Here is just for code issues, technical matters.

**Comment by kais0106** [comment]
TCdh89T1eh5as8XzHphfPL8uJSj7BaGQYt
Pada tanggal 17 Okt 2018 9:37 PM, "klix72" <notifications@github.com>
menulis:

**Comment by chairil12** [comment]
Gue mau jual 5000tau

Pada tanggal Rab, 17 Okt 2018 08.07, kais0106 <notifications@github.com>
menulis:
