### ISSUE TITLE
TAU  coin

### ISSUE THREAD

**Issue by shihann14** [Tau-Coin/taucoin#29]
really this coin so good ...the coin future so well i hope its...

**Comment by mK7768** [comment]
Ok...

**Comment by mK7768** [comment]
Im haply by TAU....

VERY GOOD.

**Comment by mK7768** [comment]
Im haply by TAU....

VERY GOOD.

**Comment by mukodas** [comment]
good

**Comment by haerul79** [comment]
Yup..

**Comment by mukodas** [comment]
https://www.taucoin.io/account/login?referralURL=a82ff4d2018ab047675ea461bf68a9be34320c2d841960e0dea31ed62ac522e2

**Comment by Morpheusai** [comment]
Thank you.Here is just for code issues, technical matters.
