### ISSUE TITLE
How do I earn money with Tau

### ISSUE THREAD

**Issue by ogbotemi-2000** [Tau-Coin/taucoin#33]
I went to the home page of the above-mentioned organisation through a link from a friend on WhatsApp with the promise of earning 75$ before the 22nd of October, tomorrow, may I have details as to how this can be done, before tomorrow, thank you

**Comment by taufiq75** [comment]
How about restart on oct 22nd

**Comment by smailmarwa** [comment]
I went to the home page of the above-mentioned organisation through a link from a friend on WhatsApp with the promise of earning 75$ before the 22nd of October, tomorrow, may I have details as to how this can be done, before tomorrow, thank you

**Comment by soegilar** [comment]
Thank you

Pada tanggal Sel, 23 Okt 2018 02:20, smailmarwa <notifications@github.com>
menulis:

**Comment by Morpheusai** [comment]
Thank you.Here is just for code issues, technical matters.
