### ISSUE TITLE
Mining..

### ISSUE THREAD

**Issue by allif11** [Tau-Coin/taucoin#7]
make it easy to mine ..

**Comment by Djekson8992** [comment]
Класс !

**Comment by Jipy77** [comment]
Ok

**Comment by raw25** [comment]
Good

**Comment by Djekson8992** [comment]
Классно !

**Comment by yasirkifli** [comment]
how to miner

**Comment by Morpheusai** [comment]
> how to miner
We have made a tutorial - how to be a miner leader in TAU, We have updated it in github, please check it.

**Comment by enal90** [comment]
Good
