### ISSUE TITLE
Can't send zero amount with taucoin-cli to start signal transaction

### ISSUE THREAD

**Issue by feyrian** [Tau-Coin/taucoin#8]
I've compiled/installed the wallet on a VPS. Can use only the taucoin-cli not the qt one.
I can't start the signal transaction because taucoin-cli returns an error when I try to send 0 TAU on my address.
```
$ taucoin-cli sendtoaddress Txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 0
error code: -3
error message:
Invalid amount for send
```

**Comment by Aungkhant2735** [comment]
😁

**Comment by Aungkhant2735** [comment]
?

**Comment by yawww** [comment]
very  nice

**Comment by feyrian** [comment]
The workaround for now is to use taucoin-qt to make the signal transaction.
You can run the wallet once on your PC, import privkey, do the signal transaction (0 TAU to yourself) close it and get back to your distant server to start mining.
Or you can stop taucoind, use ssh -X to launch taucoin-qt from your distant server on your local computer, do the signal transaction, close the ssh -X session and restart taucoind on a new ssh session.

**Comment by Morpheusai** [comment]
We upgrade the mining tutorial in our telegram, please take a check.
Taucoin-qt-> Settings-> Options-> Wallet-> enable coin control features, which will enable the inputs option in Send interface.
Taucoin-qt is recommended for signal transaction, which can ensure the input is your mining address and the output is also your mining address.

**Comment by Td10tsk** [comment]
> 
> 
> We upgrade the mining tutorial in our telegram, please take a check.
> Taucoin-qt-> Settings-> Options-> Wallet-> enable coin control features, which will enable the inputs option in Send interface.
> Taucoin-qt is recommended for signal transaction, which can ensure the input is your mining address and the output is also your mining address.

please can you write step-by-step buide?
How i can check if i mining? What i need to do exctly?

**Comment by feyrian** [comment]
@Td10tsk this is a tracker code issue, not a helpdesk channel. You have to ask on Taucoin Discord to receive help.
