### ISSUE TITLE
Command getrewardrate crash taucoind or taucoin-qt

### ISSUE THREAD

**Issue by feyrian** [Tau-Coin/taucoin#9]
Tried the command getrewardrate via taucoin-cli or console in taucoin-qt and it systematically crash.
Even with -debug option, the debug.log file show nothing.

**Comment by Morpheusai** [comment]
Yes, sir. The problem we are now fixing it. Getrewardrate will be failed when the block has no transaction, which means that there is no transaction fee in this block, so the rewarding rate is hard to calculate.
We are fixing this problem,  return the mining leader address and rewarding rate = -1.
If you have any problem, please tell us.

**Comment by feyrian** [comment]
Since 508461cd0f952b0df628b1cf51777b678a532e07 it doesn't crash anymore, but I get this error:
```error code: -8
error message:
Error: updaterewardrate default is false
```
